modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="aihkan"
version="1.0.0"
displayName="AihKan"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="darkb, MCreator"

[[dependencies.aihkan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




